spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:kopring-basic
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE