@startuml
class "Class" as c {
  +id: Long?
  +name: String
}
class "ClassRoom" as cr {
  +id: Long?
}
class "Mentor" as mr {
  +id: Long?
  +name: String
}
class "Mentee" as mt {
  +id: Long?
  +name: String
}

mr "1" --{ "1..*" c
c "1" -right-{ "0..*" cr : "\t\t"
mt "1" -left-{ "0..*" cr : "\t\t"
@enduml